### ISSUE TITLE
Still to complete?

### ISSUE THREAD

**Issue by stevenlivz** [mweibel/ejabberd-module-guide#1]
Hi - this is a neat start. I'm fairly new to ejabberd and erlang but can follow along a bit. It looks like this has still to be finished - or perhaps the intention was only as an interface/contract example? I'm trying to auth against an external Postgres DB and want to use this approach.

Actually I need to unwrap a JWT and check the validity of this before auth'ing the users xmpp session but  if i can get some kind of custom module auth working against an external db it would be a start.

Thanks for the sample!

**Comment by mweibel** [comment]
Hi,

yeah I started with this at one point because I was annoyed that no such thing exists, however I did abandon that at one point because I didn't really have time or the will to continue ;)
Also ProcessOne started to improve the documentation, so quite some things you find now on the ejabberd website: http://docs.ejabberd.im/developer/

To see how an authentication module is built, easiest is to have a look at the existing ones in the ejabberd source code.
